apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm-delete-me
data:
  service.opsgenie: |
    apiUrl: api.eu.opsgenie.corrm
    apiKeys:
      sdfgdfgdfgdfg: 2342ewewweqqrwereeeqwwwee
